version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8080:8080"
    depends_on:
      - backend
